# syntax=docker/dockerfile:1

FROM selenium/standalone-chrome:4.28.1

ARG DEBIAN_FRONTEND=noninteractive

# Install python3 and pip
RUN sudo apt-get update && \
	sudo apt-get install -y --no-install-recommends \
		python3 \
		python3-pip \
		python3-venv \
		iproute2

WORKDIR /app
